config/routes.rb
Rails.application.routes.draw do

 devise_for :customers,
             controllers: {
               sessions: 'sessions',
               registrations: 'registrations'
             }

resources :employees

post "/dashboard", to: "dashboard#dashboard"
get "dashboard", to: "dashboard#index"
get "employees", to: 'employees#index' 

get "dashboard/profiles", to: "employees#profiles"
post "dashboard", to:"dashboard#create"
# get "dashboard", to: "dashboard#show" 
get "update", to: "employees#update"
get "create", to: "dashboard#employees_create"
post "dashboard/create", to:"employees#create"
get "employee_view", to:"employees#employee_view"
# post "signup_user_create", to: "employees#signup_user_create"
get "signup", to: "employees#signup", as: "signup" 
# post "dashboard", to: "employees#dashboard"
get "dashboard/edit", to: "employees#edit"
# put "dashboard/profiles", to:"employees#update"
get "dashboard/update", to:"dashboard#update"


get "project", to:"employees#project"

resources :employees, only: [] do
  collection do
    get 'employees_by_project', to: "dashboard#project"
    get 'employees_by_name', to: "dashboard#chart"
  end
end


 # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  # protect_from_forgery with: :exception
  # before_action :authenticate_user!
end

app/models/customer.rb
class Customer < ApplicationRecord


# devise :database_authenticatable, :registerable,
# 	     :recoverable, :rememberable, :trackable,
# 	     :validatable, :email_regexp =>  /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\Z/i

  # attr_accessor :password
  EMAIL_REGEX = /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\Z/i
  validates :username, :presence => true, :uniqueness => true, :length => { :in => 3..20 }
  validates :email, :presence => true, :uniqueness => true, :format => EMAIL_REGEX
  validates :password, :confirmation => true #password_confirmation attr
  validates_length_of :password, :in => 6..20, :on => :create

  # attr_accessor :username, :email, :password, :confirm_password
  # has_secure_password
end

app/models/employee.rb
class Employee < ApplicationRecord

  validates :name, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :dob, presence: true, uniqueness: true
  validates :mobile_number, presence: true, uniqueness: true
  validates :qualification, presence: true
  validates :project, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

add_flash_types :success, :warning, :dander, :info
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
 skip_before_action :verify_authenticity_token
 # before_action :authenticate_user!

def create
  # customer = Customer.create(user_create)
end

def show
	result_array = []
  Employee.all.map do |e|
  result = {}
  result[:name] = e.name
  result[:email] = e.email
  result[:qualification] = e.qualification
  result[:dob] = e.dob
  result[:project] = e.project
  result[:mobile_number] = e.mobile_number
  result[:address] = e.address
  result_array << result
  end
  render json: [{data: result_array}]
end
# def login_attempt
#   authorized_user = Customer.authenticate(params[:email],params[:password])
#   if authorized_user
#     flash[:notice] = "Wow Welcome again, you logged in as #{authorized_user.email}"
#     redirect_to(:action => 'dashboard/emp')
#   else
#     flash[:notice] = "Invalid Email or Password"
#     flash[:color]= "invalid"
#     render "login"	
#   end
# end

def employees_create
  respond_to do |format|
    format.html 
    render  'employees/_create' 
  end
end

def project
  result = {}
  Employee.all.map do |e|
  result[e.name] = e.project
  end
  render json: result
end

def index
	 @employees = Employee.all
end

def chart
  result = {}
  Employee.all.map do |e|
  result[e.project] = e.name
  end
  render json: result
end

def update
  @employee = Employee.where(id: params[:id])
  if @employee.update(employee_create)
   render json: @employee
  else
    render :edit
  end   
end

def dashboard
  customer = Customer.create(user_create)
end


private

  def user_create
    params.require(:customer).permit(:username, :email, :password, :confirm_password)
  end

	def employee_create
		params.require(:employee).permit(:name, :email, :qualification, :dob, :project, :mobile_number)
	end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
	skip_before_action :verify_authenticity_token
 #  before_action :employee_params, only: [:edit]
	
	def index
		 @employees = Employee.last
	end

  def new
    @employee = Employee.new
  end

	def create
  	@employee = Employee.new(employee_params)
    respond_to do |format|
      if @employee.save
        format.html  { redirect_to(@employee, :notice => 'Employee was successfully created.') }
        format.json  { render :json => @employee, :status => :created, :location => @employee }
      else
        format.html  { render :action => "new" }
        format.json  { render :json => @employee.errors, :status => :unprocessable_entity }
      end
    end
  end

  def project
    result = {}
    @employees = Employee.all
    @employees.map do |e|
      result[e.name] = e.project
    end
    # render json: result
  end
  
  def show
    @employees = Employee.find(params[:id])
 
    respond_to do |format|
      format.html  # show.html.erb
      format.json  { render :json => @employees }
    end
  end
  
  def edit
    @employee = Employee.find(params[:id])
  end

  def update
  @employee = Employee.find(params[:id])
  @employee.update(employee_params)
  redirect_to employee_path(@employee)
end

  def profiles
    @employees = Employee.all
  end

  def employee_view
    @name = params[:id]
    @view_employee = Employee.find(@name)
  end

  def employees_by_project
  end

private

  def employee_params
		params.require(:employee).permit(:name, :email, :qualification, :dob, :project, :mobile_number)
	end

	# def user_create
	# 	params.require(:customer).permit(:username, :email, :password, :confirm_password)
	# end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
	
  
	def employees_by_project
    column_chart employees_by_project_employees_path library: {
      title: {text: 'Employees by project'},
      yAxis: {
         # allowDecimals: false,
         title: {
             text: 'Name'
         }
      },
      xAxis: {
        title: {
          text: 'Project count'
        }
      }
    }
  end

end

app/helpers/employees_helper.rb
module EmployeesHelper


end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/views/dashboard/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
   
 
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

<%= javascript_include_tag "http://www.google.com/jsapi", "chartkick" %>
<%= csrf_meta_tags %>

  <script type="text/javascript">
    function validate() {
        var email = document.getElementById('Email').value;
        var atpos=email.indexOf("@");
        var dotpos=email.lastIndexOf(".");


        if (atpos<1 || dotpos<atpos+2 || dotpos+2>=email.length)
          {
          alert("Not a valid e-mail address");
          return false;
          }
        return true;
    }
  </script> 

<style type="text/css">
#wrapper {
    display: flex;
    padding-left: 0;
    -webkit-transition: all 0.5s ease;
    -moz-transition: all 0.5s ease;
    -o-transition: all 0.5s ease;
    transition: all 0.5s ease;
}

#wrapper.toggled {
    padding-left: 250px;
}

#sidebar-wrapper {
    z-index: 1000;
    position: fixed;
    left: 250px;
    width: 0;
    height: 100%;
    margin-left: -250px;
    overflow-y: auto;
    background:#6699ff;
    -webkit-transition: all 0.5s ease;
    -moz-transition: all 0.5s ease;
    -o-transition: all 0.5s ease;
    transition: all 0.5s ease;
}

#wrapper.toggled #sidebar-wrapper {
    width: 250px;

}

#page-content-wrapper {
    width: 100%;
    position: absolute;
    padding: 15px;
}

#wrapper.toggled #page-content-wrapper {
    position: absolute;
    margin-right: -250px;
}


.sidebar-nav {
    position: absolute;
    top: 0px;
    width: 230px;
    margin: 0;
    padding: 20px;
    list-style: none;
}

.sidebar-nav li {
    text-indent: 20px;
    line-height: 30px;
}

.sidebar-nav li a {
    display: block;
    text-decoration: none;
    color: white;
    font-size: 20px;
}

.sidebar-nav li a:hover {
    text-decoration: none;
    color: #fff;
    background: rgba(255,255,255,0.2);
}

.sidebar-nav > .sidebar-brand {
    height: 65px;
    font-size: 20px;
    line-height: 60px;
}

.sidebar-nav > .sidebar-brand a {
    color: white;
}

.sidebar-nav > .sidebar-brand a:hover {
    /*color: #fff;*/
    background: none;
}

.sidebar-wrapper .sidebar-menu ul li:hover > a,
.sidebar-wrapper .sidebar-menu .sidebar-dropdown.active > a {
  color: #b3b8c1;
}

.sidebar-wrapper .sidebar-menu ul li a i {
  margin-right: 10px;
  font-size: 20px;
  background: #2b2b2b;
  width: 30px;
  height: 30px;
  line-height: 30px;
  text-align: center;
  border-radius: 4px;
}

.sidebar-wrapper .sidebar-menu ul li a:hover > i::before {
  animation: swing ease-in-out 0.5s 1 alternate;
}

.sidebar-wrapper .sidebar-menu .sidebar-dropdown div {
  background: #2b2b2b;
}
.sidebar-wrapper .sidebar-menu .sidebar-dropdown > a:after {
  content: "\f105";
  font-family: FontAwesome;
  font-weight: 400;
  font-style: normal;
  display: inline-block;
  text-align: center;
  text-decoration: none;
  background: 0 0;
  speak: none;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  position: absolute;
  right: 15px;
  top: 14px;
}
.sidebar-wrapper .sidebar-menu .sidebar-dropdown .sidebar-submenu ul {
  padding: 5px 0;
}

.sidebar-wrapper .sidebar-menu .sidebar-dropdown .sidebar-submenu li {
  padding-left: 25px;
  font-size: 17px;
}

.sidebar-wrapper .sidebar-menu .sidebar-dropdown .sidebar-submenu li a:before {
  content: "\f10c";
  font-family: FontAwesome;
  font-weight: 400;
  font-style: normal;
  display: inline-block;
  text-align: center;
  text-decoration: none;
  speak: none;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  margin-right: 10px;
  font-size: 10px;
}

.sidebar-wrapper .sidebar-menu ul li a span.label,
.sidebar-wrapper .sidebar-menu ul li a span.badge {
  float: right;
  margin-top: 8px;
  margin-left: 5px;
}

.sidebar-wrapper .sidebar-menu .sidebar-dropdown .sidebar-submenu li a .badge,
.sidebar-wrapper .sidebar-menu .sidebar-dropdown .sidebar-submenu li a .label {
  float: right;
  margin-top: 0px;
}

.stretch-card > .card{
  width: 100%;
  min-width: 100%;
}

.card {
  border: 0;
  background: #fff;
}
 
.card .card-body{
  padding: 2.5rem;
}

* {
  box-sizing: border-box;
}


.column {
  float: left;
  width: 25%;
  padding: 0 10px;
}

.row {margin: 0 -5px;}

.row:after {
  content: "";
  display: table;
  clear: both;
}

@media(min-width:768px) {
  #wrapper {
      padding-left: 250px;
  }

  #wrapper.toggled {
      padding-left: 0;
  }

  #sidebar-wrapper {
    width: 250px;
    margin: 62px;
    margin-left: -253px;
  }

  #wrapper.toggled #sidebar-wrapper {
      width: 0;
  }

  #page-content-wrapper {
      padding: 20px;
      position: relative;
  }

  #wrapper.toggled #page-content-wrapper {
      position: relative;
      margin-right: 0;
  }

  .column {
    width: 100%;
    display: block;
    margin-bottom: 10px;
  }
 
  h4,h3, .h3,.h4 {
    font-family: none;
    color: darkgreen;
    line-height: 1.1;
    font-weight: 500;
  }

  .card {
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
    padding: 16px;
    text-align: center;
    background-color: #f1f1f1;
  }

  .navbar {
    border-radius:0px;
  }

  .navbar {
    position: relative;
    min-height: 66px
    margin-bottom: 20px;
    border: 1px solid;
    
  }
  .navbar-right{
    margin-right: 28px;
    padding: 16px;
  }
  .navbar-inverse{
    background-color:#002266;
  }
  .navbar a {
    color: white;
  }
  .navbar-brand {
    font-size: 20px;
  }

  .btn-group button {
    background-color: #4CAF50; 
    border: 1px solid green; 
    color: white; 
    padding: 10px 24px; 
    cursor: pointer; 
    float: left; 
  }

  .btn-group button:not(:last-child) {
    border-right: none; 
  }

  .btn-group:after {
    content: "";
    clear: both;
    display: table;
  }

  .btn-group button:hover {
    background-color: #3e8e41;
  }
  .v-application .pa-3{
    padding: 12px!important;
  }
  .v-card{
    margin-top:30px;
    margin-bottom: 15px;
  }
  .theme--light.v-sheet{
    background-color: #fff;
  }
  .row{
    margin-left: 260px;
    margin-right: 590px;
  }
  h6, .h6 {
    font-size:23px;
  }
}

</style>
</head>
<body>
  <div id="wrapper" >
    <div id="sidebar-wrapper" style="font-size: 18px;">
      <nav name="dashboard" action="/dashboard"  method="post">
        <ul class="sidebar-nav">
          <li class="sidebar-brand">
            <a href="#"><i class="glyphicon glyphicon-dashboard w3-xxlarge" style="margin-right: 7px; margin-left: -35px;"></i>Dashboard</a>
          </li>
          <li class="sidebar-dropdown">
            <a href="#"><i class="glyphicon glyphicon-user" style="margin-right: 7px; icon-color; cornsilk; margin-left: -35px;"></i>Employee</a>
            <div class="sidebar-submenu" style="display: none;">
              <ul>
                <li><a href="create" class="ml-2"> Create</a></li>
              </ul>
              <ul>
                <li><a href="dashboard/profiles" onclick = "return validate()">Profiles</a></li>
              </ul>
            </div>
          </li>
          <li>
            <a href="/project"><i class="glyphicon glyphicon-credit-card" style="margin-right: 7px; icon-color; cornsilk; margin-left: -35px;"></i>Projects</a>
          </li>
        </ul>
      </nav>
    </div>
  </div>
</body>
<head>
<style type="text/css">

  .employee-form {
    width: 340px;
      margin: 50px auto;
  }
    .employee-form tr{
      margin-bottom: 15px;
        background: #f7f7f7;
        box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
        padding: 30px;
    }
    .employee-form h2 {
        margin: 0 0 15px;
    }
    .form-control, .btn {
        min-height: 38px;
        border-radius: 2px;
    }
    .btn {        
        font-size: 15px;
        font-weight: bold;
    }

    .btn {        
        font-size: 15px;
        font-weight: bold;
        width: 130px;
        height: 46px;
        margin-inline-start: 1300px;
    }
    
</style>
</head>
<body>
  <nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
    <a class="navbar-brand" style="color: white;"><span class="glyphicon glyphicon-leaf w3-xxlarge" style="width:15; margin-right: 5px;"></span> SK Solution</a>
    <div class="navbar-right" style="font-size: 20px;" >
      <a href="/employees"><span class="glyphicon glyphicon-off w3-xxlarge" style="width:15; margin-right: 10px; font-size: 20px;"></span>Logout</a>
    </div>
  </nav>

  <div class="row">
    <div class="column" style="width: 290px; height: 108px;">
      <div class="card">
        <h3><span class="glyphicon glyphicon-user"></span> EMPLOYEES</h3>
          <h4 class="align-middle"><%= Employee.count(:all)%></h4> 
      </div>
    </div>

    <div class="column" style="width: 290px; height: 108px;">
      <div class="card">
        <h3><span class="glyphicon glyphicon-credit-card"></span> PROJECTS</h3>
         <h4 class="align-middle"><%= Employee.distinct.count('project')%></h4> 
      </div>
    </div>
  </div>
</body>

  <body>
    <div id="dashboard_div" style="margin-right:600px; margin-top: 50px; padding: 20px; margin-left: 255px;" >
      <div class="card">
        <%= column_chart @employees.group(:project).count, {library: {hAxis: {title: "Projects"}, vAxis: {title: "Project Count"}}} %>
      </div>
    </div>
    <div id="dashboard_div" style="margin-right: 20px; margin-top: -370px; padding: 20px; margin-left: 850px;" >
      <div class="card">
          <%= pie_chart @employees.group(:name).count, {library: {legend: {title: "Employees By Projects"}}} %>
      </div>
    </div>
  </body>

  <script type="text/javascript">
    $(".sidebar-dropdown > a").click(function() {
    $(".sidebar-submenu").slideUp(250);
    if (
      $(this)
        .parent()
        .hasClass("active")
    ) {
      $(".sidebar-dropdown").removeClass("active");
      $(this)
        .parent()
        .removeClass("active");
    } else {
      $(".sidebar-dropdown").removeClass("active");
      $(this)
        .next(".sidebar-submenu")
        .slideDown(250);
      $(this)
        .parent()
        .addClass("active");
    }
    });

    $("#toggle-sidebar").click(function() {
      $(".page-wrapper").toggleClass("toggled");
    });
  </script>
</html>

app/views/employees/chart.html.erb
<!-- <!DOCTYPE HTML>
<html>
<head>
  <script type="text/javascript">
  window.onload = function () {
    var chart = new CanvasJS.Chart("chartContainer", {

      title:{
        text: "Employees Profiles Chart"              
      },
      data: [              
        { 
         type: "column",
         dataPoints: [
         { label: "suman", y: MedLife},
         { label: "kaleez", y: MedLife },
         { label: "karthi", y: Loyds },                                    
         ]
       }
       ]
     });

    chart.render();
  }
  </script>
  <script type="text/javascript" src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
</head>
<body>
  <div id="chartContainer" style="height: 300px; width: 100%;">
  </div>
</body>
</html> -->

<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
  <%= javascript_include_tag "http://www.google.com/jsapi", "chartkick" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= yield %>
  </div>
<div class="row" style="width:70%;">
  <div class="col-xs-6">
    <%= column_chart @employee.group(:name).count %>
  </div>
</div>
</body>
</html>

app/views/employees/edit.html.erb
<div class="container-fluid">
  <%= render 'update', employee: @employee %>
</div>

app/views/employees/new.html.erb
 
<%= render 'create' %>
 
<%= link_to 'Back', employees_path %>

app/views/employees/profiles.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


<style type="text/css">

	.table-responsive {
		min-height: .01%;
		overflow-x: auto;
		box-sizing: border-box;
	}
	.table-bordered {
		border: 1px solid #000000;
	}
	.table {
		width: 100%;
		max-width: 100%;
		margin-bottom: 20px;
	}
	table {
		border-spacing: 0;
		border-collapse: collapse;
		border: 1px solid #000000;
	}
	.table-bordered>thead>tr>td,
	.table-bordered>thead>tr>th {
		border-bottom-width: 2px;
		border: 1px solid #000000;
		padding: 8px;
		line-height: 1.428
	}
	.table>thead>tr>th {
		vertical-align: bottom;
		border: 1px solid #000000;
		padding: 8px;
		line-height: 1.428;
		text-align: center;
	}
	th {
		text-align: left;
		display: table-cell;
	}
	.thead {
		display: table-header-group;
		vertical-align: middle;
		border-color: black;
	}
	.container-fluid {
		padding-right: 15px;
		padding-left: 15px;
		margin-right: auto;
		margin-left: auto;
	}
	tbody {
		display: table-header-group;
		vertical-align: middle;
		border-color: black;
	}

	tr {
	    border: 1px solid #000000;
		display: table-row;
		vertical-align: inherit;
		border-color: black;
		text-align: center;
	}
	body {
		font-size: 20px;
		line-height: 1.426;
		color: #333;
	}

	.table-responsive table,
	.table-bordered table {
	  border-collapse: collapse;
	  
	}
	.table-bordered td,
	.table-bordered th,
	.table-responsive td,
	.table-responsive th {
	  border: 1px solid #000000;
	  padding: 5px 5px;
	}
	.table-responsive {
	  width: 120px;
	  float: left;
	  position: fixed;
	  overflow-x: scroll;
	  white-space: nowrap;
	  text-align: left;
	  border: 1px solid #000000;
	  z-index: 2;
	}
	.table-bordered {
	  width: calc(100% - 145px);
	  right: 15px;
	  position: fixed;
	  overflow-x: scroll;
	  border: 1px solid #000000;
	  white-space: nowrap;
	}
	.table-bordered td,
	.table-bordered th {
	  padding: 5px 10px;
	}

  .navbar {
		width: 1440;
		margin-left: -15px;
		height: 54;
        border-radius:0px;
        
  }

  .navbar {
    position: relative;
    min-height: 66px
    margin-bottom: 20px;
    border: 1px solid;
  }
  .navbar-brand {
  	font-size: 20px;
  }
  .navbar-right{
    margin-right: 28px;
    padding: 16px;
  }
  .navbar-inverse{
    background-color: #6699ff;
  }
  .navbar a {
    color: white;
  }
</style>
</head>

<body>
  <nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse" style="height: 68px;">
    <a class="navbar-brand" href="/dashboard#" style="color: white; margin: 8px;"><span class="glyphicon glyphicon-leaf w3-xxlarge" style="width:15px; margin-right: 5px;"></span> SK Solution</a>
    <h3 class="text-center" style="color: white;">Employee Details</h3> 
    <div class="navbar-right" style="margin-top: -55px;">
      <a href="/employees"><span class="glyphicon glyphicon-off w3-xxlarge" style="width:15; margin-right: 10px; "></span>Logout</a>
    </div>
  </nav>
	<div class="container-fluid" style="width: 2%;">
 <!--  <div class="table-responsive" style="display: block;"> -->
	  <table class="table table-bordered table-hover" style="border-color: black;">
	    <thead class="thead-light" style="color: white; background-color: #6699ff;">
	      <tr style="border: 5px;" >
	        <th scope="col" style="min-width: 100px">Name</th> 
	        <th scope="col" style="min-width: 100px">Email</th> 
	        <th scope="col" style="min-width: 100px">Qualification </th>
	        <th scope="col" style="min-width: 100px">Dob</th> 
	        <th scope="col" style="min-width: 100px">Project</th>
	        <th scope="col" style="min-width: 100px">Mobile Number</th>
	      </tr>
	    </thead>
	    <tbody>
	      <% @employees.each do |p| %> 
	      <tr id="header_<%= p.id %>" class="element-row">
		    <!-- <input type="hidden" id="employee" value="<%= p.id %>"> -->
	        <td class=" align-middle" id="name"><%= p.name %></td> 
	        <td class="align-middle" id="email"><%= p.email %></td>  
	        <td class="align-middle" id="qualification"><%= p.qualification %></td> 
	        <td class="align-middle" id="dob"><%= p.dob%></td> 
	        <td class="align-middle" id="project"><%= p.project%></td> 
	        <td class="align-middle" id="project"><%= p.mobile_number%></td>
	        <td><a href="edit" class="glyphicon glyphicon-pencil w3-xxxlarge"></a></td>
          <% end %> 
        </tr>
      </tbody>
	  </table> 
	<!-- </div>     -->
  </div>
</body>
</html> 